<<<<<<< HEAD
require("chas.plugins-setup")
require("chas.core.options")
require("chas.core.keymaps")
require("chas.core.colorscheme")
require("chas.plugins.comment")
require("chas.plugins.nvim-tree")
require("chas.plugins.lualine")
require("chas.plugins.telescope")
require("chas.plugins.nvim-cmp")
require("chas.plugins.lsp.mason")
require("chas.plugins.lsp.lspsaga")
require("chas.plugins.lsp.lspconfig")
=======
require("plugins-setup")
require("core.options")
require("core.keybindings")
require("core.colorscheme")
require("plugins.lsp")
require("plugins.lualine")
require("plugins.nvim-tree")
--require("plugins.nvim-cmp")
require("plugins.telescope")
require("plugins.harpoon")
require("plugins.treesitter")
>>>>>>> 2f6273e (initial commit)
